// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd2x5p68zG3NoWDZS6CJhS_c6sPfxMaX0',
    appId: '1:527163525459:web:321ee0e2cf0cf0313479a6',
    messagingSenderId: '527163525459',
    projectId: 'traffatt',
    authDomain: 'traffatt.firebaseapp.com',
    storageBucket: 'traffatt.firebasestorage.app',
    measurementId: 'G-Z24LYFSMJ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlP4G9Db_RzUR_V-oErns3JOTt3wzgg78',
    appId: '1:527163525459:android:fd4bd0f3f19122bc3479a6',
    messagingSenderId: '527163525459',
    projectId: 'traffatt',
    storageBucket: 'traffatt.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoRd0mSVxQBoaH6_ccIs87vBneCQeJgxk',
    appId: '1:527163525459:ios:42485f4765707c1f3479a6',
    messagingSenderId: '527163525459',
    projectId: 'traffatt',
    storageBucket: 'traffatt.firebasestorage.app',
    iosBundleId: 'com.example.traffAttNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoRd0mSVxQBoaH6_ccIs87vBneCQeJgxk',
    appId: '1:527163525459:ios:42485f4765707c1f3479a6',
    messagingSenderId: '527163525459',
    projectId: 'traffatt',
    storageBucket: 'traffatt.firebasestorage.app',
    iosBundleId: 'com.example.traffAttNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCd2x5p68zG3NoWDZS6CJhS_c6sPfxMaX0',
    appId: '1:527163525459:web:321ee0e2cf0cf0313479a6',
    messagingSenderId: '527163525459',
    projectId: 'traffatt',
    authDomain: 'traffatt.firebaseapp.com',
    storageBucket: 'traffatt.firebasestorage.app',
    measurementId: 'G-Z24LYFSMJ7',
  );
}
